/* Congreso: las participaciones son filas nuevas; nombre_mesa nunca se reutiliza. */
(function ($) {
  'use strict';
  var endpoint='../ajax/congreso.php', context=null, listContext=null;
  function request(data) { return $.ajax({url:endpoint,type:'POST',data:data,dataType:'json'}); }
  function subject() { return Number($('#id_usuario').attr('name'))||0; }
  function esc(value) { return $('<div>').text(value == null ? '' : String(value)).html(); }
  function roleText(tipo) { return Number(tipo)===1 ? ['Coordinador/a','Coorganizador/a','Otros Organizadores','Nombre Mesa/Simposio','Comentarista'] : ['Autor/a','Coautor/a','Otros Coautores',Number(tipo)===3?'Nombre Poster':'Nombre Mesa/Simposio',Number(tipo)===3?'':'Nombre Ponencia']; }
  function getContext() { if(context)return $.Deferred().resolve(context).promise(); return request({op:'context'}).then(function(r){if(r.status!=='OK')return $.Deferred().reject(r);context=r.data;return context;}); }
  function dataBase(op) { var d={op:op,csrf:context.csrf_token}; if(context.can_manage_global)d.subject_usuario_id=subject(); return d; }
  function roleBlock(labels,data) { var p=data||{},role=Number($('#rol_cong').val()),label=role===1?labels[1]:labels[0],id=role===1?p.id_coaut:p.id_aut,name=role===1?(p.nom_coaut||p.nombre_coaut_interno):(p.nom_aut||p.nombre_aut_interno),contrary=role?'<label for="persona_contraria" class="form-label">'+label+'</label><input id="persona_contraria" class="form-control academic-search" maxlength="60" autocomplete="off" value="'+esc(name||'')+'"><input type="hidden" class="academic-id" value="'+esc(id||'')+'"><small class="academic-selected" data-id="'+esc(id||'')+'">'+esc(id?name:'')+'</small><ul class="list-group academic-results mt-1"></ul>':'';return '<fieldset id="role-block" class="border rounded p-3 mb-3 participant-block"><legend class="float-none w-auto px-2 fs-6">Participación principal</legend><div class="row"><div class="col-md-6 mb-3"><label for="rol_cong" class="form-label">Rol en la participación</label><select id="rol_cong" class="form-select"><option value="0">Seleccione</option><option value="1" '+(role===1?'selected':'')+'>'+labels[0]+'</option><option value="2" '+(role===2?'selected':'')+'>'+labels[1]+'</option></select></div></div>'+contrary+'</fieldset>'; }
  function participantForm(tipo, data) { var labels=roleText(tipo),p=data||{};return '<div id="part" data-id="'+esc(p.id_participacion||'')+'">'+roleBlock(labels,p)+'<div class="row"><div class="col-md-6 mb-3"><label>'+labels[3]+'</label><input id="nombre_mesa" maxlength="45" class="form-control" value="'+esc(p.nombre_mesa||'')+'"></div>'+(Number(tipo)===3?'':'<div class="col-md-6 mb-3"><label>'+labels[4]+'</label><input id="coment_ponenc" maxlength="80" class="form-control" value="'+esc(p.coment_ponenc||'')+'"></div>')+'</div><div class="row"><div class="col-md-6 mb-3"><label>Tipo</label><select id="tipo_cong" class="form-select"><option value="0">Seleccione</option><option value="1" '+(Number(p.tipo_cong)===1?'selected':'')+'>Mesa</option><option value="2" '+(Number(p.tipo_cong)===2?'selected':'')+'>Simposio</option></select></div></div><div class="mb-3"><label>'+labels[2]+' <small>(separados por coma, opcional)</small></label><textarea id="otros_org" maxlength="300" class="form-control">'+esc(p.otros_org||'')+'</textarea></div></div>'; }
  window.formCongreso=function(container) { $(container).append('<div class="row"><div class="col-md-6 mb-3"><label>Nombre</label><input id="nom_cong" class="form-control" maxlength="60" autocomplete="off"><ul id="list_cong" class="list-group"></ul></div><div class="col-md-6 mb-3"><label>Ciudad</label><input id="ciudad_cong" class="form-control" maxlength="45"></div></div><div class="row"><div class="col-md-6 mb-3"><label>Fecha Inicio</label><input id="fech_in_cong" type="date" class="form-control"></div><div class="col-md-6 mb-3"><label>Fecha Término</label><input id="fech_ter_cong" type="date" class="form-control"></div></div><div id="participation-choice"></div><div class="mb-3"><label>Participación</label><select id="cong" class="form-select"><option value="0">Seleccione</option><option value="1">Coordinación</option><option value="2">Expositor/a</option><option value="3">Presentación Póster</option></select></div><div id="id_cong"></div><div id="mnsj_row_cong" class="alert d-none"><span id="mnsj_cong"></span></div>'); };
  window.formParticipacion=function(data){var tipo=Number($('#cong').val());$('#id_cong').html(tipo?participantForm(tipo,data):'');};
  function formData() { var tipo=Number($('#cong').val()),rol=Number($('#rol_cong').val()),$role=$('#role-block'),id=Number($role.find('.academic-selected').data('id'))||null,nombre=$.trim($('#persona_contraria').val()||''),d={tipo_part:tipo,tipo_cong:Number($('#tipo_cong').val()),nombre_mesa:$.trim($('#nombre_mesa').val()),coment_ponenc:tipo===3?'':$.trim($('#coment_ponenc').val()||''),otros_org:$.trim($('#otros_org').val()||'')};if(rol===1){d.id_aut=subject();d.nom_aut='';d.id_coaut=id||'';d.nom_coaut=id?'':nombre;}else if(rol===2){d.id_aut=id||'';d.nom_aut=id?'':nombre;d.id_coaut=subject();d.nom_coaut='';}return d; }
  function message(text,ok){$('#mnsj_row_cong').removeClass('d-none alert-danger alert-success').addClass(ok?'alert-success':'alert-danger');$('#mnsj_cong').text(text);}
  function clearSelectedCongress(){
    if(!Number($('#nom_cong').data('id')))return;
    $('#nom_cong').removeData('id');
    $('#ciudad_cong,#fech_in_cong,#fech_ter_cong').prop('disabled',false).val('');
    $('#participation-choice').empty();
    $('#cong').val('0');
    $('#id_cong').empty();
  }
  function refresh(){if(listContext)window.cargarCong(listContext.usuario,listContext.destino);}
  function zonaCongreso(){return $('#form_congreso').closest('.oa-zone');}
  function closeCreate(){var $card=$('#ingresar_congreso');$card.find('input,textarea,select').val('');$card.remove();var $zona=zonaCongreso();if($zona.length){$zona.find('.oa-editor').hide();$zona.find('.oa-list,.oa-add').show();}else $('#boton_congreso,#boton_publicacion').show();}
  function openCreate(){if($('#ingresar_congreso').length)return;var $box=$('#congreso').first();if(!$box.length)return;var $zona=zonaCongreso();if($zona.length){$zona.find('.oa-list,.oa-add,.oa-editor').hide();$('#form_congreso').show();}else $('#boton_congreso,#boton_publicacion').hide();$box.empty().append('<div class="card mb-3" id="ingresar_congreso"><div class="card-body"><div class="row justify-content-between"><div class="col-auto mb-3"><h4 class="card-title">Congreso</h4></div><div class="col-auto"><button type="button" class="btn btn-close btn-sm cancelar-congreso" aria-label="Cerrar"></button></div></div><div id="congreso-form-fields"></div></div><div class="card-footer text-end"><button class="btn btn-dark" id="guardar_congreso" type="button">Guardar Congreso</button></div></div>');if(!$('#ingresar_congreso').length)return;formCongreso('#congreso-form-fields');document.getElementById('ingresar_congreso').scrollIntoView({behavior:'smooth',block:'start'});}
  $(document).on('click','#btn_congreso',function(){getContext().then(openCreate);});
  $(document).on('change','#cong',function(){formParticipacion();});
  $(document).on('change','#rol_cong',function(){var tipo=Number($('#cong').val());if(tipo)$('#role-block').replaceWith(roleBlock(roleText(tipo)));});
  $(document).on('input','#nom_cong',function(){var q=$.trim(this.value),list=$('#list_cong').empty();if(q.length<2)return;request({op:'search',q:q}).then(function(r){(r.data||[]).forEach(function(c){$('<li>',{class:'list-group-item congress-option'}).text(c.nombre).data('congreso',c).appendTo(list);});});});
  $(document).on('click','.congress-option',function(){var c=$(this).data('congreso');$('#nom_cong').val(c.nombre).data('id',c.id_congreso).prop('readonly',false);$('#ciudad_cong').val(c.ciudad).prop('disabled',true);$('#fech_in_cong').val(c.fecha_inicio).prop('disabled',true);$('#fech_ter_cong').val(c.fecha_termino).prop('disabled',true);$('#list_cong').empty();var d=dataBase('detail');d.id_congreso=c.id_congreso;request(d).then(function(r){var html='<label class="form-label">Participaciones</label><div class="mb-3">';(r.data.participaciones||[]).forEach(function(p){html+='<button type="button" class="btn btn-outline-secondary me-2 mb-2 select-participation" data-id="'+p.id_participacion+'">Participación #'+p.id_participacion+'</button>';});html+='<button type="button" class="btn btn-outline-primary mb-2 new-participation">Nueva Participación</button></div>';$('#participation-choice').html(html);$('#cong,#rol_cong').val('0');$('#id_cong').empty();});});
  $(document).on('click','.new-participation',function(){$('#cong,#rol_cong').val('0');$('#id_cong').empty();});
  $(document).on('click','.select-participation',function(){var button=$(this),d=dataBase('participation_detail');d.id_participacion=Number(button.data('id'));request(d).then(function(r){var p=r.data,l=roleText(p.tipo_part),html='<div class="alert alert-info participation-detail"><strong>Participación #'+esc(p.id_participacion)+'</strong><br>Tipo: '+esc(Number(p.tipo_cong)===1?'Mesa':'Simposio')+'<br>'+esc(l[3])+': '+esc(p.nombre_mesa)+(Number(p.tipo_part)===3?'':'<br>'+esc(l[4])+': '+esc(p.coment_ponenc))+'<br>'+esc(l[0])+': '+esc(p.nom_aut||p.id_aut)+'<br>'+esc(l[1])+': '+esc(p.nom_coaut||p.id_coaut)+'<br>'+esc(l[2])+': '+esc(p.otros_org||'')+'</div>',target=$('#id_cong');if(target.length)target.html(html);else button.closest('.card-body').find('.participation-detail').remove().end().append(html);});});
  /* A manual metadata edit invalidates the explicit Congreso selection. */
  $(document).on('input','#ciudad_cong,#fech_in_cong,#fech_ter_cong',clearSelectedCongress);
  $(document).on('input','#nom_cong',function(){
    clearSelectedCongress();
    var q=$.trim(this.value),list=$('#list_cong').empty();
    if(q.length<2){list.hide();return;}
    request({op:'search',q:q}).then(function(r){
      list.empty();
      (r.data||[]).forEach(function(c){
        $('<li>',{class:'list-group-item congress-option'})
          .text(c.nombre)
          .data('congreso',c).appendTo(list);
      });
    });
  });
  $(document).on('click','.congress-option',function(){
    var c=$(this).data('congreso');
    $('#nom_cong').val(c.nombre).data('id',c.id_congreso).prop('disabled',false);
    $('#ciudad_cong').val(c.ciudad).prop('disabled',true);
    $('#fech_in_cong').val(c.fecha_inicio).prop('disabled',true);
    $('#fech_ter_cong').val(c.fecha_termino).prop('disabled',true);
    var d=dataBase('detail');d.id_congreso=c.id_congreso;
    request(d).then(function(r){
      var html='<div class="alert alert-info mb-3">Modo: nueva Participación en Congreso existente.</div><label class="form-label">Mis Participaciones en este Congreso</label><div class="mb-3">';
      (r.data.participaciones||[]).forEach(function(p){html+='<button type="button" class="btn btn-outline-secondary me-2 mb-2 select-participation" data-id="'+p.id_participacion+'">Participación #'+p.id_participacion+'</button>';});
      html+='<button type="button" class="btn btn-outline-primary mb-2 new-participation">Nueva Participación</button></div>';
      $('#participation-choice').html(html);$('#cong,#rol_cong').val('0');$('#id_cong').empty();
    });
  });
  /* Capture phase prevents the legacy autocomplete handlers from racing this flow. */
  document.addEventListener('input',function(event){
    if(!event.target.matches('#nom_cong,#ciudad_cong,#fech_in_cong,#fech_ter_cong'))return;
    event.stopImmediatePropagation();
    clearSelectedCongress();
    if(!event.target.matches('#nom_cong'))return;
    var q=$.trim(event.target.value),list=$('#list_cong').empty().show();
    if(q.length<2){list.hide();return;}
    request({op:'search',q:q}).then(function(r){
      list.empty();
      list.show();
      (r.data||[]).forEach(function(c){$('<li>',{class:'list-group-item congress-option'}).text(c.nombre).data('congreso',c).appendTo(list);});
    });
  },true);
  document.addEventListener('click',function(event){
    var option=event.target.closest('.congress-option');
    if(!option)return;
    event.stopImmediatePropagation();
    var c=$(option).data('congreso');
    $('#nom_cong').val(c.nombre).data('id',c.id_congreso).prop('disabled',false);
    $('#ciudad_cong').val(c.ciudad).prop('disabled',true);
    $('#fech_in_cong').val(c.fecha_inicio).prop('disabled',true);
    $('#fech_ter_cong').val(c.fecha_termino).prop('disabled',true);
    $('#list_cong').empty();
    var d=dataBase('detail');d.id_congreso=c.id_congreso;
    request(d).then(function(r){
      var html='<div class="alert alert-info mb-3">Modo: nueva Participación en Congreso existente.</div><label class="form-label">Mis Participaciones en este Congreso</label><div class="mb-3">';
      (r.data.participaciones||[]).forEach(function(p){html+='<button type="button" class="btn btn-outline-secondary me-2 mb-2 select-participation" data-id="'+p.id_participacion+'">Participación #'+p.id_participacion+'</button>';});
      html+='<button type="button" class="btn btn-outline-primary mb-2 new-participation">Nueva Participación</button></div>';
      $('#participation-choice').html(html);$('#cong,#rol_cong').val('0');$('#id_cong').empty();
    });
  },true);
  $(document).on('input','.academic-search',function(){var $b=$(this).closest('.participant-block'),q=$.trim(this.value),list=$b.find('.academic-results').empty().hide();$b.find('.academic-id').val('');$b.find('.academic-selected').text('').data('id',null);if(q.length<2)return;request({op:'academic_user_search',q:q}).then(function(r){(r.data||[]).forEach(function(u){if(Number(u.id_usuario)!==subject())$('<li>',{class:'list-group-item academic-option'}).text(u.nombre).data({id:Number(u.id_usuario),nombre:u.nombre}).appendTo(list);});list.toggle(list.children().length>0);});});
  $(document).on('click','.academic-option',function(){var u=$(this).data(),b=$(this).closest('.participant-block');b.find('.academic-search').val(u.nombre);b.find('.academic-id').val(u.id);b.find('.academic-selected').text(u.nombre).data('id',u.id);b.find('.academic-results').empty().hide();});
  $(document).on('click','#guardar_congreso',function(){getContext().then(function(){var existing=Number($('#nom_cong').data('id'))||0,d=dataBase(existing?'participation_create':'create');if(existing)d.id_congreso=existing;else $.extend(d,{nombre:$.trim($('#nom_cong').val()),ciudad:$.trim($('#ciudad_cong').val()),fecha_inicio:$('#fech_in_cong').val(),fecha_termino:$('#fech_ter_cong').val()});$.extend(d,formData());request(d).then(function(r){if(r.status==='OK'){closeCreate();refresh();}else message(r.message||'No fue posible guardar.',false);},function(xhr){message(xhr.responseJSON&&xhr.responseJSON.message||'No fue posible guardar.',false);});});});
  $(document).on('click','.cancelar-congreso',function(){closeCreate();});
  function actorName(p, role){return Number(role===1?p.id_aut:p.id_coaut)?(role===1?p.nombre_aut_interno:p.nombre_coaut_interno):(role===1?p.nom_aut:p.nom_coaut);}
  function participationTitle(p){return (Number(p.tipo_part)===1?'Coordinación':Number(p.tipo_part)===2?'Expositor/a':'Presentación Póster')+' — '+(p.nombre_mesa||'Sin nombre');}
  function participationTable(p){var labels=roleText(p.tipo_part),fields=[['Tipo',Number(p.tipo_cong)===1?'Mesa':'Simposio'],[labels[3],p.nombre_mesa],[labels[0],actorName(p,1)],[labels[1],actorName(p,2)],[labels[2],p.otros_org]];if(Number(p.tipo_part)!==3)fields.splice(2,0,[labels[4],p.coment_ponenc]);var $table=$('<table>',{class:'table table-striped mb-2'}),$body=$('<tbody>');fields.forEach(function(field){if(field[1])$body.append($('<tr>').append($('<td>').text(field[0]),$('<td>').text(field[1])));});return $table.append($body);}
  function congressCard(c, parts){var $card=$('<div>',{class:'card mb-3 card_pub'}),$body=$('<div>',{class:'card-body'}),$table=$('<table>',{class:'table table-striped'}),$head=$('<thead>').append($('<tr>').append($('<th>').append($('<h5>').text(c.nombre))));$table.append($head,$('<tbody>').append($('<tr>').append($('<td>').text('Ciudad'),$('<td>').text(c.ciudad)), $('<tr>').append($('<td>').text('Fecha inicio'),$('<td>').text(c.fecha_inicio)), $('<tr>').append($('<td>').text('Fecha término'),$('<td>').text(c.fecha_termino))));$body.append($table,$('<h6>',{class:'mt-3'}).text('Participaciones'));parts.forEach(function(p){var collapseId='congreso-participacion-'+c.id_congreso+'-'+p.id_participacion,$button=$('<button>',{type:'button',class:'btn btn-link ps-0 participation-toggle','data-bs-toggle':'collapse','data-bs-target':'#'+collapseId,'aria-expanded':'false','aria-controls':collapseId}).text(participationTitle(p)),$detail=$('<div>',{id:collapseId,class:'collapse'}).append(participationTable(p));if(context.can_manage_global)$detail.append($('<button>',{type:'button',class:'btn btn-link link-success ps-0 congress-edit'}).text('Editar participación').data('id',p.id_participacion),$('<button>',{type:'button',class:'btn btn-link link-danger ps-1 participation-delete'}).text('Eliminar participación').data('id',p.id_participacion));$body.append($('<div>',{class:'border-top pt-2 mt-2','data-id-participacion':p.id_participacion}).append($button,$detail));});if(context.can_manage_global)$body.append($('<button>',{type:'button',class:'btn btn-link link-success ps-0 congress-update'}).text('Editar Congreso').data('congreso',{id_congreso:c.id_congreso,nombre:c.nombre,ciudad:c.ciudad,fecha_inicio:c.fecha_inicio,fecha_termino:c.fecha_termino}),$('<button>',{type:'button',class:'btn btn-link link-danger ps-1 congress-delete'}).text('Eliminar Congreso').data('id',c.id_congreso));return $card.append($body);}
  function congressCard(c, parts){
    var $card=$('<div>',{class:'card mb-3 card_pub'}),$body=$('<div>',{class:'card-body'}),$table=$('<table>',{class:'table table-striped'}),$controls=$('<th>',{class:'row justify-content-end ps-0 botones'}),$head=$('<thead>').append($('<tr>').append($('<th>').append($('<h5>').text('CONGRESO')),$controls));
    if(context.can_manage_global)$controls.append($('<button>',{type:'button',class:'col-auto btn btn-link link-success ps-1 congress-update'}).text('Editar').data('congreso',{id_congreso:c.id_congreso,nombre:c.nombre,ciudad:c.ciudad,fecha_inicio:c.fecha_inicio,fecha_termino:c.fecha_termino}),$('<button>',{type:'button',class:'col-auto btn btn-link link-danger ps-1 congress-delete'}).text('Eliminar').data('id',c.id_congreso));
    $table.append($head,$('<tbody>').append($('<tr>').append($('<td>').text('Nombre'),$('<td>').text(c.nombre)),$('<tr>').append($('<td>').text('Ciudad'),$('<td>').text(c.ciudad)),$('<tr>').append($('<td>').text('Fecha inicio'),$('<td>').text(c.fecha_inicio)),$('<tr>').append($('<td>').text('Fecha término'),$('<td>').text(c.fecha_termino))));
    $body.append($table,$('<h6>',{class:'mt-3 fs-5'}).text('Participaciones'));
    parts.forEach(function(p){var collapseId='congreso-participacion-'+c.id_congreso+'-'+p.id_participacion,$button=$('<button>',{type:'button',class:'btn btn-link text-dark fs-5 ps-0 participation-toggle','data-bs-toggle':'collapse','data-bs-target':'#'+collapseId,'aria-expanded':'false','aria-controls':collapseId}).text(participationTitle(p)),$detail=$('<div>',{id:collapseId,class:'collapse'}).append(participationTable(p));$body.append($('<div>',{class:'border-top pt-2 mt-2','data-id-participacion':p.id_participacion}).append($button,$detail));});
    return $card.append($body);
  }
  window.cargarCong=function(usuario,destino){listContext={usuario:Number(usuario)||subject(),destino:destino};getContext().then(function(){var d={op:'list'};if(context.can_manage_global)d.subject_usuario_id=listContext.usuario;request(d).then(function(r){var by={},rows=r.data||[],$target=$(listContext.destino).empty();if(!rows.length){$target.append($('<p>',{class:'text-muted mb-3',text:'No hay Congresos registrados.'}));return;}rows.forEach(function(p){(by[p.id_congreso]||(by[p.id_congreso]={c:p,p:[]})).p.push(p);});Object.keys(by).forEach(function(k){$target.append(congressCard(by[k].c,by[k].p));});});});};
  $(document).on('click','.participation-delete,.congress-delete',function(){var part=$(this).hasClass('participation-delete'),id=$(this).data('id');if(!window.confirm(part?'¿Eliminar sólo esta Participación?':'¿Eliminar el Congreso y sus Participaciones?'))return;getContext().then(function(){var d=dataBase(part?'participation_delete':'delete');d[part?'id_participacion':'id_congreso']=id;request(d).then(function(r){if(r.status==='OK')refresh();else window.alert(r.message||'No fue posible eliminar.');});});});
  $(document).on('click','.congress-update',function(){var c=$(this).data('congreso'),nombre=window.prompt('Nombre del Congreso',c.nombre);if(nombre===null)return;var ciudad=window.prompt('Ciudad',c.ciudad);if(ciudad===null)return;var inicio=window.prompt('Fecha inicio (AAAA-MM-DD)',c.fecha_inicio);if(inicio===null)return;var termino=window.prompt('Fecha término (AAAA-MM-DD)',c.fecha_termino);if(termino===null)return;getContext().then(function(){var d=dataBase('update');$.extend(d,{id_congreso:c.id_congreso,nombre:nombre,ciudad:ciudad,fecha_inicio:inicio,fecha_termino:termino});request(d).then(function(r){if(r.status==='OK')refresh();else window.alert(r.message||'No fue posible actualizar.');});});});
  $(document).on('click','.congress-edit',function(){var id=Number($(this).data('id')),card=$(this).closest('.card');getContext().then(function(){var d=dataBase('participation_detail');d.id_participacion=id;request(d).then(function(r){var p=r.data,role=Number(p.id_aut)===subject()?1:2;$('#congreso-admin-editor').remove();var host=$('<div id="congreso-admin-editor" class="card mb-3"><div class="card-body"></div></div>').insertBefore(card).find('.card-body');host.html('<form id="form_edit_congreso" data-participacion="'+id+'"><button type="button" class="btn-close float-end cancelar-editor-participacion"></button><h4>Editar Participación</h4><select id="cong" class="form-select mb-3"><option value="1">Coordinación</option><option value="2">Expositor/a</option><option value="3">Presentación Póster</option></select><div class="mb-3"><label>Rol propio</label><select id="rol_cong" class="form-select"><option value="1">Rol 1</option><option value="2">Rol 2</option></select></div><div id="id_cong"></div><button class="btn btn-dark" type="submit">Guardar cambios</button></form>');$('#cong').val(p.tipo_part);$('#rol_cong').val(role);formParticipacion(p);});});});
  $(document).on('click','.cancelar-editor-participacion',function(){$(this).closest('#congreso-admin-editor').remove();});
  $(document).on('submit','#form_edit_congreso',function(e){e.preventDefault();var form=$(this),d=dataBase('participation_update');d.id_participacion=Number(form.data('participacion'));$.extend(d,formData());request(d).then(function(r){if(r.status==='OK'){form.closest('#congreso-admin-editor').remove();refresh();}else window.alert(r.message||'No fue posible actualizar.');},function(xhr){window.alert(xhr.responseJSON&&xhr.responseJSON.message||'No fue posible actualizar.');});});
  function restoreCongressList(){var $zona=zonaCongreso();if($zona.length)$zona.find('.oa-add').show();else $('#boton_congreso').show();if(listContext)window.cargarCong(listContext.usuario,listContext.destino);}
  function openCongressEditor(c){zonaCongreso().find('.oa-add').hide();var d=dataBase('detail');d.id_congreso=c.id_congreso;request(d).then(function(r){var x=r.data,$target=$(listContext.destino).empty(),$view=$('<div>',{id:'congreso-editor',class:'card mb-3 card_pub','data-congreso':x.id_congreso}),$body=$('<div>',{class:'card-body'});$body.append($('<div>',{class:'row justify-content-between'}).append($('<div>',{class:'col-auto mb-3'}).append($('<h4>',{class:'card-title'}).text('EDITAR CONGRESO')),$('<div>',{class:'col-auto'}).append($('<button>',{type:'button',class:'btn btn-close btn-sm cancelar-editor-congreso','aria-label':'Cancelar'}))),$('<div>',{class:'row'}).append(editInput('Nombre','edit_nombre_congreso',x.nombre),editInput('Ciudad','edit_ciudad_congreso',x.ciudad),editInput('Fecha inicio','edit_inicio_congreso',x.fecha_inicio,'date'),editInput('Fecha término','edit_termino_congreso',x.fecha_termino,'date')),$('<button>',{type:'button',class:'btn btn-dark guardar-congreso-edicion'}).text('Guardar Congreso'),$('<button>',{type:'button',class:'btn btn-link cancelar-editor-congreso'}).text('Cancelar'),$('<h5>',{class:'mt-4'}).text('Participaciones'));(x.participaciones||[]).forEach(function(p){$body.append($('<div>',{class:'border-top pt-2 mt-2'}).append($('<span>').text(participationTitle(p)),$('<button>',{type:'button',class:'btn btn-link link-success ps-2 editar-participacion-vista'}).text('Editar').data('id',p.id_participacion)));});$body.append($('<div>',{id:'editor-participacion'}));$target.append($view.append($body));document.getElementById('congreso-editor').scrollIntoView({behavior:'smooth',block:'start'});});}
  $(document).on('ajaxSuccess',function(){
    $('#congreso-editor .editar-participacion-vista').each(function(){var $edit=$(this);if($edit.siblings('.eliminar-participacion-vista').length)return;$('<button>',{type:'button',class:'btn btn-link link-danger ps-2 eliminar-participacion-vista'}).text('Eliminar').data('id',$edit.data('id')).insertAfter($edit);});
  });
  function editInput(label,id,value,type){return $('<div>',{class:'col-md-6 mb-3'}).append($('<label>',{for:id,class:'form-label'}).text(label),$('<input>',{id:id,type:type||'text',class:'form-control'}).val(value||''));}
  function openParticipationEditor(id){var d=dataBase('participation_detail');d.id_participacion=id;request(d).then(function(r){var p=r.data,role=Number(p.id_aut)===subject()?1:2,$box=$('#editor-participacion').empty().append($('<div>',{class:'card mt-3'}).append($('<div>',{class:'card-body'})));$box.find('.card-body').append($('<div>',{class:'row justify-content-between'}).append($('<div>',{class:'col-auto mb-3'}).append($('<h4>',{class:'card-title'}).text('EDITAR PARTICIPACIÓN')),$('<div>',{class:'col-auto'}).append($('<button>',{type:'button',class:'btn btn-close btn-sm cancelar-editor-participacion','aria-label':'Cancelar'}))),$('<select>',{id:'cong',class:'form-select mb-3'}).append($('<option>',{value:1}).text('Coordinación'),$('<option>',{value:2}).text('Expositor/a'),$('<option>',{value:3}).text('Presentación Póster')).val(p.tipo_part),$('<div>',{id:'id_cong'}),$('<button>',{type:'button',class:'btn btn-dark guardar-participacion-edicion'}).text('Guardar Participación'),$('<button>',{type:'button',class:'btn btn-link cancelar-editor-participacion'}).text('Cancelar'));formParticipacion(p);$('#rol_cong').val(role);$('#role-block').replaceWith(roleBlock(roleText(p.tipo_part),p));});}
  $(document).off('click','.congress-update').on('click','.congress-update',function(){openCongressEditor($(this).data('congreso'));});
  $(document).off('click','.congress-edit').on('click','.congress-edit',function(){openParticipationEditor(Number($(this).data('id')));});
  $(document).on('click','.editar-participacion-vista',function(){openParticipationEditor(Number($(this).data('id')));});
  $(document).on('click','.eliminar-participacion-vista',function(){var id=Number($(this).data('id')),congresoId=Number($('#congreso-editor').data('congreso'));if(!id||!congresoId||!window.confirm('¿Está seguro de eliminar esta Participación?'))return;getContext().then(function(){var d=dataBase('participation_delete');d.id_participacion=id;request(d).then(function(r){if(r.status==='OK'){$('#editor-participacion').empty();openCongressEditor({id_congreso:congresoId});}else window.alert(r.message||'No fue posible eliminar la Participación.');},function(x){window.alert(x.responseJSON&&x.responseJSON.message||'No fue posible eliminar la Participación.');});});});
  $(document).on('click','.guardar-congreso-edicion',function(){var d=dataBase('update');$.extend(d,{id_congreso:Number($('#congreso-editor').data('congreso')),nombre:$.trim($('#edit_nombre_congreso').val()),ciudad:$.trim($('#edit_ciudad_congreso').val()),fecha_inicio:$('#edit_inicio_congreso').val(),fecha_termino:$('#edit_termino_congreso').val()});request(d).then(function(r){if(r.status==='OK')restoreCongressList();else window.alert(r.message||'No fue posible actualizar.');},function(x){window.alert(x.responseJSON&&x.responseJSON.message||'No fue posible actualizar.');});});
  $(document).on('click','.guardar-participacion-edicion',function(){var d=dataBase('participation_update');d.id_participacion=Number($('#id_cong #part').data('id'));$.extend(d,formData());request(d).then(function(r){if(r.status==='OK')restoreCongressList();else window.alert(r.message||'No fue posible actualizar.');},function(x){window.alert(x.responseJSON&&x.responseJSON.message||'No fue posible actualizar.');});});
  $(document).on('click','.cancelar-editor-congreso',restoreCongressList);
  $(document).off('click','.cancelar-editor-participacion').on('click','.cancelar-editor-participacion',function(){$('#editor-participacion').empty();});
})(jQuery);
