(function ($) {
  'use strict';
  const endpoint='../ajax/proyecto.php';
  const state={context:null,target:'#proyecto_card',subject:null};
  function request(data,write){const o={url:endpoint,type:'POST',dataType:'json',data:data};if(write&&state.context)o.headers={'X-CSRF-Token':state.context.csrf_token};return $.ajax(o).then(r=>r&&r.ok?r:$.Deferred().reject({responseJSON:r}).promise());}
  function context(){if(state.context)return $.Deferred().resolve(state.context).promise();return request({op:'context'}).then(r=>{state.context=r.datos;return state.context;});}
  function error(x){return x&&x.responseJSON&&x.responseJSON.mensaje||'No fue posible completar la operación.';}
  function val(x){return x==null?'':String(x);}
  function cardText(x){return typeof x==='string'&&x.trim()!==''?cadenaMay(x):'';}
  function escText(text){return $('<div>').text(val(text)).html();}
  function actorRole(){return $('#proyecto-rol-propio').val();}
  function person(prefix,label,data,locked,insideColumn){data=data||{};let text=data.id?data.nombre:(data.nombre_externo||''),classes=(insideColumn?'':'col-md-6 mb-3 ')+'proyecto-persona';return '<div class="'+classes+'" data-prefix="'+prefix+'"><label class="form-label">'+label+'</label><input class="form-control proyecto-persona-texto" maxlength="60" autocomplete="off" value="'+escText(text)+'" '+(locked?'disabled':'')+'><input type="hidden" class="proyecto-persona-id" value="'+escText(data.id||'')+'"><ul class="list-group proyecto-resultados" style="display:none"></ul></div>';}
  function options(rows,id,label,empty){let out='<option value="">'+empty+'</option>';(rows||[]).forEach(x=>out+='<option value="'+Number(x[id])+'">'+escText(x[label])+'</option>');return out;}
  function catalogs(){return $.when($.ajax({url:'../ajax/financiamiento.php',type:'POST',dataType:'json',data:{op:'read-project',subject_usuario_id:state.subject}}),$.ajax({url:'../ajax/institucion.php',type:'POST',dataType:'json',data:{op:'read'}}));}
  function form(row,position){context().then(()=>catalogs()).then((fin,inst)=>{const global=state.context.can_manage_global;row=row||{};const creating=!row.id_proyecto;let inv={id:row.id_inv,nombre:row.investigador_interno,nombre_externo:row.nom_inv},co={id:row.id_coinv,nombre:row.coinvestigador_interno,nombre_externo:row.nom_coinv};let html='<div class="card mb-3" id="proyecto-editor"><div class="card-body"><div class="d-flex justify-content-between"><div><h4>Proyecto Investigación</h4><small class="text-muted">'+(row.id_proyecto?'Editar Proyecto':'Crear Proyecto')+'</small></div><button type="button" class="btn-close proyecto-cancelar"></button></div><div class="row"><div class="col-md-4 mb-3"><label>Folio</label><input id="proyecto-folio" class="form-control" maxlength="10" value="'+escText(row.folio)+'"></div><div class="col-md-4 mb-3"><label>Año</label><input id="proyecto-anio" type="number" class="form-control" value="'+escText(row.anio_adjud)+'"></div><div class="col-md-4 mb-3"><label>Duración (meses)</label><input id="proyecto-duracion" type="number" class="form-control" value="'+escText(row.duracion)+'"></div><div class="col-12 mb-3"><label>Título</label><textarea id="proyecto-titulo" class="form-control" maxlength="300">'+escText(row.titulo)+'</textarea></div><div class="col-md-6 mb-3"><label>Financiamiento</label><select id="proyecto-financiamiento" class="form-select">'+options(fin[0],'id_financ','financiamiento','Seleccione')+'</select></div><div class="col-md-6 mb-3"><label>Institución del Coinvestigador</label><select id="proyecto-institucion" class="form-select">'+options(inst[0],'id_inst','inst','Sin institución')+'</select></div></div>';
      if(creating)html+='<div class="row"><div class="col-6 mb-3"><label class="form-label">Rol</label><select id="proyecto-rol-propio" class="form-select"><option value="">Seleccione</option><option value="investigador">Investigador</option><option value="coinvestigador">Coinvestigador</option></select></div><div class="col-6 mb-3 d-none" id="proyecto-contraparte"></div></div>';else if(global)html+='<div class="row">'+person('investigador','Investigador',inv)+person('coinvestigador','Coinvestigador',co)+'</div>';
      html+='<div class="alert alert-danger d-none proyecto-mensaje"></div><button type="button" class="btn btn-dark proyecto-guardar" data-id="'+(row.id_proyecto||'')+'">Guardar</button></div></div>';$(state.target).html(html);$('#proyecto-financiamiento').val(row.fuente_financiamiento||'');$('#proyecto-institucion').val(row.inst_proy||'');if(position)document.getElementById('proyecto-editor').scrollIntoView({behavior:'smooth',block:'start'});if(!global&&row.id_proyecto){};});}
  function personData(prefix){const box=$('.proyecto-persona[data-prefix="'+prefix+'"]'),id=Number(box.find('.proyecto-persona-id').val())||'',text=$.trim(box.find('.proyecto-persona-texto').val());return {[prefix+'_usuario_id']:id,[prefix+'_nombre_externo']:id?'':text};}
  function payload(id){let p={folio:$.trim($('#proyecto-folio').val()),titulo:$.trim($('#proyecto-titulo').val()),anio_adjud:$('#proyecto-anio').val(),duracion:$('#proyecto-duracion').val(),fuente_financiamiento:$('#proyecto-financiamiento').val(),inst_proy:$('#proyecto-institucion').val()||''};if(id)$.extend(p,personData('investigador'),personData('coinvestigador'));else{let role=actorRole(),other=personData('contraparte');$.extend(p,{subject_usuario_id:state.subject,subject_role:role});if(role==='investigador')$.extend(p,{investigador_usuario_id:state.subject,investigador_nombre_externo:'',coinvestigador_usuario_id:other.contraparte_usuario_id,coinvestigador_nombre_externo:other.contraparte_nombre_externo});else if(role==='coinvestigador')$.extend(p,{coinvestigador_usuario_id:state.subject,coinvestigador_nombre_externo:'',investigador_usuario_id:other.contraparte_usuario_id,investigador_nombre_externo:other.contraparte_nombre_externo});}return p;}
  function render(rows){const target=$(state.target).empty();(rows||[]).forEach(r=>{let inv=cardText(r.id_inv?r.investigador_interno:r.nom_inv),co=cardText(r.id_coinv?r.coinvestigador_interno:r.nom_coinv);let body=$('<div>',{class:'card-body'}),card=$('<div>',{class:'card mb-3 card_pub'}).append(body),controls=$('<th>',{class:'row justify-content-end ps-0 botones'}),head=$('<thead>').append($('<tr>').append($('<th>',{class:'col-md-4 titulo_acad'}).append($('<h5>').text('PROYECTO INVESTIGACIÓN')),controls));let table=$('<table>',{class:'table table-striped'}),tableBody=$('<tbody>');[['Folio',cardText(r.folio)],['Título',cardText(r.titulo)],['Año',r.anio_adjud],['Duración',r.duracion ? r.duracion+' meses' : r.duracion],['Financiamiento',cardText(r.financiamiento)],['Investigador',inv],['Coinvestigador',co],['Institución del Coinvestigador',cardText(r.institucion_coinvestigador)]].forEach(x=>{if(x[1])tableBody.append($('<tr>').append($('<td>').text(x[0]),$('<td>').text(x[1])));});if(state.context.can_manage_global)controls.append($('<button>',{class:'col-auto btn btn-link link-success ps-1 proyecto-editar'}).text('Editar').data('id',r.id_proyecto),$('<button>',{class:'col-auto btn btn-link link-danger ps-1 proyecto-eliminar'}).text('Eliminar').data('id',r.id_proyecto));table.append(head,tableBody);body.append(table);target.append(card);});}
  function load(){const $zona=$(state.target).closest('.oa-zone');if($zona.length)$zona.find('.oa-add').show();else $('#boton_proyecto').show();context().then(()=>request({op:'list',subject_usuario_id:state.subject})).then(r=>{if(!Array.isArray(r.datos)||r.datos.length===0){$(state.target).empty().append($('<p>',{class:'text-muted mb-3',text:'No hay Proyectos de Investigación registrados.'}));return;}render(r.datos);}).fail(x=>$(state.target).text(error(x)));}
  window.cargarProy=function(usuario,destino){state.subject=Number(usuario)||null;state.target=destino||'#proyecto_card';load();};
  $(document).on('click','#btn_proyecto',function(){context().then(()=>{if(!state.subject&&!state.context.can_manage_global)return;const $zona=$(state.target).closest('.oa-zone');if($zona.length)$zona.find('.oa-add').hide();else $('#boton_proyecto').hide();form(undefined,true);});});
  $(document).on('change','#proyecto-rol-propio',function(){let role=this.value,label=role==='investigador'?'Coinvestigador':role==='coinvestigador'?'Investigador':'';$('#proyecto-contraparte').toggleClass('d-none',!label).html(label?person('contraparte',label,undefined,false,true):'');});
  $(document).on('input','.proyecto-persona-texto',function(){let b=$(this).closest('.proyecto-persona'),list=b.find('.proyecto-resultados');b.find('.proyecto-persona-id').val('');let q=$.trim(this.value);list.empty().hide();if(q.length<2)return;$.ajax({url:'../ajax/publicacion.php',type:'POST',dataType:'json',data:{op:'academic_user_search',q:q}}).then(r=>{if(!r||r.status!=='OK')return;(r.data||[]).forEach(u=>$('<li>',{class:'list-group-item proyecto-usuario'}).text(u.nombre).data(u).appendTo(list));list.toggle(list.children().length>0);},()=>list.empty().hide());});
  $(document).on('click','.proyecto-usuario',function(){let b=$(this).closest('.proyecto-persona'),u=$(this).data();b.find('.proyecto-persona-texto').val(u.nombre);b.find('.proyecto-persona-id').val(u.id_usuario);b.find('.proyecto-resultados').empty().hide();});
  $(document).on('click','.proyecto-guardar',function(){let id=Number($(this).data('id'))||0,p=payload(id);p.op=id?'update':'create';if(id)p.id_proyecto=id;request(p,true).then(()=>{ $('#proyecto-editor').remove(); load(); }).fail(x=>$('.proyecto-mensaje').text(error(x)).removeClass('d-none'));});
  $(document).on('click','.proyecto-editar',function(){let id=Number($(this).data('id'));const $zona=$(state.target).closest('.oa-zone');if($zona.length)$zona.find('.oa-add').hide();else $('#boton_proyecto').hide();context().then(()=>request({op:'detail',id_proyecto:id})).then(r=>form(r.datos,true));});
  $(document).on('click','.proyecto-eliminar',function(){let id=Number($(this).data('id'));if(!window.confirm('¿Eliminar este Proyecto de Investigación?'))return;request({op:'delete',id_proyecto:id},true).then(()=>load()).fail(x=>window.alert(error(x)));});
  $(document).on('click','.proyecto-cancelar',load);
}(jQuery));
